### ISSUE TITLE
サーバーが重い

### ISSUE THREAD

**Issue by kutouten** [kutouten/MCBattleRoyale#16]
メモリ割り当てが2GBなので増やす。fillがずっと動いてるのも原因かも

**Comment by taku1417** [comment]
メモリ不足だけでなくCPUの性能不足もありそう
もしそうならconohaで立てるなど対策可能なので相談お願いします...

**Comment by kutouten** [comment]
描画、演算距離を10chankから6chankに変更
まだ重いようなら4chankにします
