### ISSUE TITLE
補助アイテム系のナーフ

### ISSUE THREAD

**Issue by sean20010930** [kutouten/MCBattleRoyale#17]
コストと効果が釣り合ってない気がしました。
シールドバッテリーは現在10増えてるハートを5～7くらいにするかクラフトに使うラピスブロックの数を増やした方がいいと思いました。
プロテインに関しては使わなかったので憶測で語りますが、ダメージ20%カットが1分持続するのはコストにしては強すぎな気がします。20～30秒程がいいかもしれません。

**Comment by kutouten** [comment]
コストを重くするより、効果を薄くする方向で調整予定
